stages:
  - name: Publish spring image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        pushRemote: true
        registry: 10.20.0.73:32443
      env:
        PLUGIN_BUILD_ARGS: --progress=tty --network=host
        PLUGIN_DEBUG: "true"
        PLUGIN_INSECURE: "true"
        #PLUGIN_MIRROR: http://10.20.0.73:32443/
        PLUGIN_MTU: "1000"

  # (選擇性)部屬使用者的資料庫
  - name: Deploy db
    steps:
      - applyAppConfig:
          catalogTemplate: cattle-global-data:iii-dev-charts3-db
          version: 0.1.0
          name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
          targetNamespace: ${CICD_GIT_REPO_NAME}
          answers:
            git.host: "10.20.0.73"
            # 這裡是為了告訴要處理的git來源為何
            git.repoName: ${CICD_GIT_REPO_NAME}
            git.branch: ${CICD_GIT_BRANCH}
            db.type: postgresql
            db.gui: true
            # 使用者資料庫管理密碼
            db.username: bear
            db.password: bearisbear
            # 使用者初始想要建立的資料庫名稱
            db.name: health  

  # 部屬使用者應用(app)
  - name: Deploy app-web
    steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-web
        version: 0.2.1
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web
        #targetNamespace: p-v2nzs-pipeline
        targetNamespace: ${CICD_GIT_REPO_NAME}
        answers:
          xip.ip: "10.20.0.74"
          harbor.host: "10.20.0.73:32443"
          # 基礎pipeline參數
          git.host: "10.20.0.73"
          git.url: ${CICD_GIT_URL}
          git.branch: ${CICD_GIT_BRANCH}
          git.commitID: ${CICD_GIT_COMMIT}
          git.repoName: ${CICD_GIT_REPO_NAME}
          # web參數設定
          web.type: spring
          # 10.50.1.63:5443/app/${CICD_GIT_REPO_NAME}-web
          web.image: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}
          web.tag: ${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}


